name: train
 
on:
  workflow_dispatch:
    inputs:
      exp_run_args:
        type: string
        description: 'Any args to pass to dvc exp run'
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  run:
    environment: aws
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
 
      - uses: iterative/setup-dvc@v1
 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 3600
 
      - name: train
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVCLIVE_LOG_LEVEL: DEBUG
          DVC_STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
        run: |
          pip install --upgrade -r requirements.txt

          dvc pull --allow-missing
          dvc exp run --queue ${{ inputs.exp_run_args }}
          dvc exp run --run-all
          dvc exp push -v -A origin
